import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import PrelineScript from "@/components/PrelineScript";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/navbar.tsx/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={inter.className}>
      <ClerkProvider>
        <Toaster position="top-center"  toastOptions={{
    className: '',
    style: {
      textAlign:"center",
      border: '1px solid #713200',
      padding: '16px',
      color: 'black',
    },
  }}/>   
  <Navbar  />
        {children}
        </ClerkProvider>
        </body>
        <PrelineScript />

    </html>
  );
}
